spring:
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://119.29.0.241:1433;DatabaseName=parking
        username: jztda
        password: Aa12345678
        dbType: sqlserver


server:
    port: 8091
    servlet:
        context-path: /api
logging:
    level:
        com:
            zp:
                parking:
                    mapper: debug

